apiVersion: v1
kind: Service
metadata:
  name: myntra-service
  labels:
    app: myntra
spec:
  type: NodePort
  selector:
    app: myntra
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000  # Optional: remove this line to auto-assign a port in 30000–32767 range
